import React, {useEffect, useState} from 'react';
import Head from 'next/head';

const MyComponent = () => {

  const[elementContent, setElementContent] = useState("No element");

  useEffect(()=>{
    const element=document.getElementById("text");
    if(element){
      setElementContent(element.textContent);
    }
  }, []);
  return (
      <div className='text' id='text'>
        <h1 className='text-center m-2 p-2'>Welcome to my First App in NextJS</h1>
      </div>
  );
};

export default function Home(){


  const [docEnv, setDocEnv] = useState(false);

    useEffect(() => {
        if (typeof document !== "undefined") {
            setDocEnv(true);
        }
    }, []);
    return (
        <>
            <Head>
                <title>My First App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div
                    style={{
                        minHeight: "100vh",
                        backgroundColor: "white",
                        color: "black",
                    }}
                >
                    {docEnv && <MyComponent />}
                </div>
            </main>
        </>
    );
}
