import Head from 'next/head'


export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text">
        Hello World.
      </div> */}
      <Head>
        <title>My First App</title>
      </Head>
      <div className='text'>
        <h1>Welcome to my First App in NextJS</h1>
      </div>
    </div>
  )
}
